#!/usr/bin/env python3
# =============================================================================
# run_hls.py — SSM_accel Vitis HLS 2025.1 runner
# Generates a TCL script and invokes vitis-run --mode hls --tcl
# Adapted from TellMe_Infra/hw/hls/script/run_hls.py
# =============================================================================

import argparse
import os
import shutil
import subprocess
import sys

# Template for the Tcl script. Placeholders in {} will be replaced.
TCL_TEMPLATE = """
# Vitis HLS Tcl script generated by run_hls.py (SSM_accel / Vitis 2025.1)
#
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.

# 1. Create/open the project.
open_project "{project_path}"

# 2. Add design source files.
{add_source_files}

# 3. Add test bench files.
{add_tb_files}

# 4. Set the top-level function.
set_top {top_function}

#########################################################
# 5. Create a solution or open an existing one.
open_solution {solution_name} -flow_target vitis -reset

# 6. Target hardware part and clock.
set_part {{{part}}}
create_clock -period {clock_period}

# 7. Select HLS flow steps.
#    0: C Synthesis only (default)
#    1: C Simulation
#    2: C Synthesis and Co-simulation
#    3: C Synthesis and IP Export (impl)
#    4: Full flow (C-sim, Synth, Co-sim, IP Export with impl)
#    5: Full flow (C-sim, Synth, Co-sim, IP Export with synth)
#    6: C Synthesis and IP Export (syn only)
#    7: C Synthesis and IP Export (syn + impl)
#    8: C Synthesis and IP Export (no impl/syn flow)
#    9: C-sim + Synthesis + IP Export (syn, no Co-sim)
set hls_exec {hls_exec}

# 8. Optimization directives.
config_array_partition -throughput_driven off
config_interface -m_axi_buffer_impl bram
config_export -vivado_clock {vivado_clock_period}

# 8b. Co-simulation depth for raw-pointer (m_axi) ports that have no
#     array-dimension to infer from.  The depth must be >= the maximum
#     number of DTYPE_VEC elements the kernel can read/write in one call.
#     HUGE_LEN = STATE_T * C2_T = 16 * 640 = 10240 vectors.
set_directive_interface -mode m_axi -depth 10240 "{top_function}" C_ddr
set_directive_interface -mode m_axi -depth 10240 "{top_function}" H1_ddr

# 9. Execute the selected flow.
if {{ {hls_exec} == 1 }} {{
    csim_design -ldflags {{-z stack-size=10485760}}

}} elseif {{ {hls_exec} == 2 }} {{
    csynth_design
    cosim_design -ldflags {{-z stack-size=10485760}}

}} elseif {{ {hls_exec} == 3 }} {{
    csynth_design
    export_design -flow impl -output "{project_path}/{solution_name}/impl/export.zip"
}} elseif {{ {hls_exec} == 4 }} {{
    csim_design -ldflags {{-z stack-size=10485760}}
    csynth_design
    cosim_design -ldflags {{-z stack-size=10485760}}
    export_design -flow impl
}} elseif {{ {hls_exec} == 5 }} {{
    csim_design -ldflags {{-z stack-size=10485760}}
    csynth_design
    cosim_design -ldflags {{-z stack-size=10485760}}
    export_design -flow syn
}} elseif {{ {hls_exec} == 6 }} {{
    csynth_design
    export_design -flow syn
}} elseif {{ {hls_exec} == 7 }} {{
    csynth_design
    export_design -flow syn
    export_design -flow impl
}} elseif {{ {hls_exec} == 8 }} {{
    csynth_design
    export_design
}} elseif {{ {hls_exec} == 9 }} {{
    csim_design -ldflags {{-z stack-size=10485760}}
    csynth_design
    export_design -flow syn
}} else {{
    csynth_design
}}

# Synthesis report location:
# {project_path}/{solution_name}/syn/report/{top_function}_csynth.rpt

exit
"""


def run_hls_flow(args):
    """Generates the Tcl script and runs Vitis HLS 2025.1."""
    print(f"--- Generating Tcl script: {args.tcl_script} ---")

    # Format source and testbench file commands.
    if args.cflags:
        source_files_str = "\n".join(
            [f'add_files {f} -cflags "{args.cflags}"' for f in args.source_files]
        )
        tb_files_str = "\n".join(
            [f'add_files -tb {f} -cflags "{args.cflags}"' for f in args.tb_files]
        )
    else:
        source_files_str = "\n".join([f"add_files {f}" for f in args.source_files])
        tb_files_str = "\n".join([f"add_files -tb {f}" for f in args.tb_files])

    # Ensure log directory exists.
    log_dir = os.path.dirname(args.log_file)
    if log_dir and not os.path.exists(log_dir):
        print(f"Creating log directory: {log_dir}")
        os.makedirs(log_dir)

    # Fill in the Tcl template.
    tcl_content = TCL_TEMPLATE.format(
        project_path=args.project_path,
        add_source_files=source_files_str,
        add_tb_files=tb_files_str,
        top_function=args.top_function,
        solution_name=args.solution_name,
        part=args.part,
        clock_period=args.clock_period,
        vivado_clock_period=args.vivado_clock_period,
        hls_exec=args.hls_exec,
    )

    with open(args.tcl_script, "w") as f:
        f.write(tcl_content)
    print(f"Successfully generated {args.tcl_script}")

    # --- Execute Vitis HLS 2025.1 ---
    # Vitis 2025.1 uses: vitis-run --mode hls --tcl <file>
    # Fallback to vitis_hls --classic -f <file> if vitis-run not found.
    vitis_run = shutil.which("vitis-run")
    if vitis_run:
        command = ["vitis-run", "--mode", "hls", "--tcl", args.tcl_script]
    else:
        # Fallback for older Vitis versions
        print("[WARN] 'vitis-run' not found, falling back to 'vitis_hls --classic'")
        command = ["vitis_hls", "--classic", "-f", args.tcl_script, "-l", args.log_file]

    try:
        print(f"\n--- Running Vitis HLS: {' '.join(command)} ---")
        print(f"--- Log file: {args.log_file} ---")

        # Tee output to both console and log file
        with open(args.log_file, "w") as logf:
            proc = subprocess.Popen(
                command,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
            )
            for line in proc.stdout:
                sys.stdout.write(line)
                logf.write(line)
            proc.wait()

        if proc.returncode != 0:
            print(f"\n[ERROR] Vitis HLS failed with exit code {proc.returncode}.")
        else:
            print("--- Vitis HLS executed successfully ---")

    except FileNotFoundError:
        print("\n[ERROR] Neither 'vitis-run' nor 'vitis_hls' found in PATH.")
        print("Please source Vitis 2025.1: source /tools/Xilinx/2025.1/Vitis/settings64.sh")
    finally:
        if not args.persistent and os.path.exists(args.tcl_script):
            os.remove(args.tcl_script)
            print(f"\n--- Removed temporary script: {args.tcl_script} ---")
        elif args.persistent:
            print(f"\n--- Tcl script kept: {args.tcl_script} ---")

        print(f"\n--- Process Finished ---")
        print(f"Project: {args.project_path}")
        print(f"Reports: {args.project_path}/{args.solution_name}/syn/report/")
        if args.hls_exec in [3, 4, 5, 6, 7, 8, 9]:
            print(f"IP Export: {args.project_path}/{args.solution_name}/impl/")


def clean_files(args):
    """Cleans up generated files and directories."""
    print("--- Cleaning up generated files ---")

    if os.path.exists(args.tcl_script):
        os.remove(args.tcl_script)
        print(f"Removed: {args.tcl_script}")

    if os.path.exists(args.project_path):
        shutil.rmtree(args.project_path)
        print(f"Removed project directory: {args.project_path}")

    if os.path.exists(args.log_file):
        os.remove(args.log_file)
        print(f"Removed log file: {args.log_file}")

    log_dir = os.path.dirname(args.log_file)
    try:
        if log_dir and os.path.exists(log_dir) and not os.listdir(log_dir):
            os.rmdir(log_dir)
            print(f"Removed empty log directory: {log_dir}")
    except OSError as e:
        print(f"Could not remove log directory {log_dir}: {e}")

    print("Cleanup complete.")


def main():
    """Main function to parse arguments and execute the HLS flow."""
    ssm_home = os.environ.get("SSM_HOME")
    if not ssm_home:
        print("[ERROR] SSM_HOME environment variable is not set.", file=sys.stderr)
        print(
            "Please set it: export SSM_HOME=/home/chouy/SSM_accel", file=sys.stderr
        )
        sys.exit(1)
    if not os.path.isdir(ssm_home):
        print(
            f"[ERROR] SSM_HOME directory does not exist: {ssm_home}", file=sys.stderr
        )
        sys.exit(1)

    parser = argparse.ArgumentParser(
        description="Generate a Tcl script and run Vitis HLS 2025.1. Paths relative to SSM_HOME.",
        formatter_class=argparse.RawTextHelpFormatter,
    )

    gen_group = parser.add_argument_group("HLS Project Arguments")
    gen_group.add_argument("--project_name", type=str, help="HLS project directory name.")
    gen_group.add_argument(
        "--source_files", type=str, nargs="+", help="Source files (relative to SSM_HOME)."
    )
    gen_group.add_argument(
        "--tb_files", type=str, nargs="+", help="Testbench files (relative to SSM_HOME)."
    )
    gen_group.add_argument("--top_function", type=str, help="Top-level function name.")
    gen_group.add_argument(
        "--cflags", type=str, default="", help="Additional C compile flags."
    )
    gen_group.add_argument(
        "--solution_name", type=str, default="solution1", help="Solution name (default: solution1)."
    )
    gen_group.add_argument(
        "--part",
        type=str,
        default="xck26-sfvc784-2LV-c",
        help="Target FPGA part (default: xck26-sfvc784-2LV-c).",
    )
    gen_group.add_argument(
        "--clock_period", type=float, default=2.5, help="HLS clock period in ns (default: 2.5)."
    )
    gen_group.add_argument(
        "--vivado_clock_period",
        type=str,
        default="4ns",
        help="Vivado clock period for export (default: 4ns).",
    )
    gen_group.add_argument(
        "--hls_exec",
        type=int,
        default=0,
        choices=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        help="Execution mode:\n"
        "0: Synthesis only (default)\n"
        "1: C simulation\n"
        "2: Synthesis + Co-simulation\n"
        "3: Synthesis + IP Export (impl)\n"
        "4: Full flow (C-sim, Synth, Co-sim, IP Export impl)\n"
        "5: Full flow (C-sim, Synth, Co-sim, IP Export synth)\n"
        "6: Synthesis + IP Export (syn only)\n"
        "7: Synthesis + IP Export (syn + impl)\n"
        "8: Synthesis + IP Export (fastest)\n"
        "9: C-sim + Synthesis + IP Export (syn, no Co-sim)",
    )

    file_group = parser.add_argument_group("File and Cleanup Arguments")
    file_group.add_argument(
        "--tcl_script",
        type=str,
        default="run_hls.tcl",
        help="Temporary Tcl script name (default: run_hls.tcl).",
    )
    file_group.add_argument(
        "--log_file",
        type=str,
        default=None,
        help="Log file path relative to SSM_HOME.",
    )
    file_group.add_argument(
        "-p", "--persistent", action="store_true", help="Keep Tcl script after execution."
    )
    file_group.add_argument(
        "--clean", action="store_true", help="Clean all generated files for project_name."
    )

    args = parser.parse_args()

    # Post-process paths to absolute based on SSM_HOME
    if args.project_name:
        args.project_path = os.path.join(
            ssm_home, "hw/hls/syn_result", args.project_name
        )

    if args.log_file is None:
        if args.project_name:
            args.log_file = os.path.join(
                ssm_home, "hw/hls/log", f"{args.project_name}_{args.solution_name}.log"
            )
    else:
        args.log_file = os.path.join(ssm_home, args.log_file)

    if args.clean:
        if not args.project_name:
            parser.error("--project_name is required when using --clean.")
        clean_files(args)
    else:
        required_args = ["project_name", "source_files", "tb_files", "top_function"]
        if not all(getattr(args, arg) for arg in required_args):
            parser.error(
                "Required: --project_name, --source_files, --tb_files, --top_function"
            )

        # Convert to absolute paths
        args.source_files = [os.path.join(ssm_home, f) for f in args.source_files]
        args.tb_files = [os.path.join(ssm_home, f) for f in args.tb_files]

        run_hls_flow(args)


if __name__ == "__main__":
    main()
